version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "n8n", "-d", "n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"      # nur lokal – extern über Reverse Proxy
    env_file:
      - stack.env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
  n8n_data:
