version: "3.8"

services:
  n8n:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"        # nur lokal erreichbar :contentReference[oaicite:6]{index=6}
    env_file: .env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "n8n", "-d", "n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  n8n_data:
  pg_data:
